### ISSUE TITLE
Undefined index: UserId

### ISSUE THREAD

**Issue by kingispeak** [tsaiyihua/laravel-ecpay#1]
環境：
Laravel 5.8 homestead

按照範例使用時
呼叫 `$this->checkout->setPostData($formData)->send();`

出現錯誤 Undefined index: UserId
CheckoutPostCollection.php  function optimize() 126行

想請問如何處理

**Comment by tsaiyihua** [comment]
$formData 再加一個 UserId
這個主要是要帶商店用戶的ID給 ecpay, 在寫程式時,我先在測試裡寫死, 範例裡忘了寫了.

**Comment by kingispeak** [comment]
感謝 @tsaiyihua，已正常。
