### ISSUE TITLE
退款問題

### ISSUE THREAD

**Issue by kevin700523** [tsaiyihua/laravel-ecpay#10]
非常感謝您提供這個好用的套件省下很多介接綠界金流的時間

想請問下，不知道是否也可以提供退款的範例呢？
謝謝您

**Comment by tsaiyihua** [comment]
綠界沒有提供測試環境的退款方法，所以我也沒有寫相關的方法，因為無法驗證。
退款的相關文件在 https://www.ecpay.com.tw/Content/files/ecpay_012.pdf ，你可以參考看看。
