### ISSUE TITLE
About setting returnUrl and notifyUrl

### ISSUE THREAD

**Issue by kingispeak** [tsaiyihua/laravel-ecpay#2]
想請問
我去設置了自己的 return url 和 notify url
`return $this->checkout->setNotifyUrl(route('notify'))->setReturnUrl(route('return'))->setPostData($formData)->send();`

輸入卡號與手機驗證碼後，成功轉回自己的網站 /return 時，出現 419逾時
我看 Log  notify 和 return 都沒成功進入的樣子

我這邊的理解
notify 應該會收到綠界回傳的 post date，然後我們要回傳 ok
return 則是綠界會導到該頁，讓站方可以秀結帳成功的畫面

但不知道哪個環節有問題？導致這個狀況發生
再麻煩了，需要更多資訊的話我再提供
感謝

**Comment by tsaiyihua** [comment]
你的理解沒有錯，只是注意一點，在收到 Server 端付款結果通知後，需正確回應 1|OK

而 419 的錯誤可能是 laravel csrf 檢查的錯誤，要避免這個錯誤，可以在 VerifyCsrfToken 的 Middleware 裡，將你的 notify url 及 return url 設在 $except 裡。
ex:
`
    protected $except = [
        'donate/notify', 'donate/return', 'donate/customer'
    ];
`

**Comment by kingispeak** [comment]
感謝 @tsaiyihua 幫忙，確實是 csrf 的問題，已解決。
這個套件省下不少接金流的時間，非常感謝。

**Comment by kingispeak** [comment]
另外想再詢問 
`$this->checkout->setPostData($formData)->send();`

最後會到 `view('ecpay::send', $data);` 直接 submit form 到綠界 
請問這部分目前有提供我們可以取得 $data ，在自己的網站前端實作嗎？

**Comment by tsaiyihua** [comment]
我把使用自己的  submit form 的方法加進去了。
- 方法一： 在 .env 裡使用 ECPAY_SEND_FORM 的環境變數來指定。
- 方法二： 直接指定 ECPay::$sendForm 的值來指定。

**Comment by kingispeak** [comment]
感謝
