### ISSUE TITLE
小小問題 

### ISSUE THREAD

**Issue by zhi8617** [tsaiyihua/laravel-ecpay#20]
https://github.com/tsaiyihua/laravel-ecpay/blob/57ef94d7a8a6f127fdf1a73bac752a7fbca79788/src/Http/Controllers/ECPayController.php#LL42C9-L42C55

我查看在您寫的範例裡面, 裡面有這行
我想請問，要傳什麼參數過去 它才會有回傳 redirect 這個傳數

**Comment by tsaiyihua** [comment]
你要送給綠界的 ReturnURL 裡，直接帶 redirect 這個參數並指向你要帶回自己本地端的 URL

**Comment by zhi8617** [comment]
哈哈 耍笨了我 
那時候一直專注在綠界的文件 。
忘記這個基本功能。 謝謝您
