### ISSUE TITLE
2.4.9 的 Laravel 相依性是 9.0

### ISSUE THREAD

**Issue by Mowd** [tsaiyihua/laravel-ecpay#22]
2.4.9 修正了 Donation 不應等於 2 的問題
但是相依性變成了 "laravel/framework": "^9.0"
有機會改成 2.4.8 的 "laravel/framework": "^6|7.30.4|^8.40.0" ？

**Comment by tsaiyihua** [comment]
感謝，已修正。
2.x 新版本 2.4.10
