### ISSUE TITLE
查詢訂單問題

### ISSUE THREAD

**Issue by j2ian** [tsaiyihua/laravel-ecpay#4]
當我使用範例如:
        $formData = ['orderId'=>'O154320382117474878'];
        return $this->queryTradeInfo->getData($formData)->query();.
顯示錯誤
Array to string conversion在StringService.php 的$checkCodeStr .= '&'.$key.'='.$val;

我嘗試做一些修正，但顯示
ECPayException
HTTP Error with code 0

想請教如何修正才能正確查詢訂單內容?

**Comment by tsaiyihua** [comment]
Sorry, 我範例寫錯了，查詢訂單時，只要代入訂單ID就可以了。
ex: 
```php
$orderId' = 'O154320382117474878';
return $this->queryTradeInfo->getData($orderId)->query();.
```
