### ISSUE TITLE
InvoicePostCollection can`t get Checkout`s MerchantTradeNo

### ISSUE THREAD

**Issue by silviayc** [tsaiyihua/laravel-ecpay#5]
InvoicePostCollection.php Line 70-71
Need to change to
`$this->put('RelateNumber', $this->attributes['MerchantTradeNo']??StringService::identifyNumberGenerator('O'));`

InvoicePostCollection.php Line 189
Need to change to
`$this->put('RelateNumber', $this->attributes['MerchantTradeNo']??StringService::identifyNumberGenerator('O'));`

**Comment by tsaiyihua** [comment]
Thanks for your report.

I had fixed it and release to 2.1 version
