### ISSUE TITLE
關於超商付款的回傳值

### ISSUE THREAD

**Issue by vicbear** [tsaiyihua/laravel-ecpay#8]
先感謝作者大大的分享。

目前遇到使用超商條碼或ATM 付款成功後沒有回寫到資料庫，但是信用卡刷卡又是正常，一直找不出原因，想請大大指點迷津XD

**Comment by tsaiyihua** [comment]
這套件沒有寫入資料庫的功能，所以不能寫入的部分我沒法幫你測，我只能測試到在綠界後台點模擬付款後，會 post 資料回 /ecpay/notify，然後其結果是 200 ok，然後綠界後台顯示付款 完成。

要寫入資料庫的話，你需要改寫 /ecpay/notify 的方法，除了回傳 '1|OK' 外，另外再加上寫入資料庫的功能。

**Comment by tsaiyihua** [comment]
沒其他問題的話，這 issue 我就關囉。

**Comment by zhi8617** [comment]
題外話，小孩好可愛。

**Comment by tsaiyihua** [comment]
> 題外話，小孩好可愛。

謝謝 :)
